name: Deploy in Production

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  test-in-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo"
      - name: Mostrar fecha y hora del sistema
        run: date
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install express js
        run: npm install express --save
      - name: Build
        run: npm run build
      # - name: Unit test
      #   run: 
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ~/apps/ts-api-newspaper-cd &&
            git checkout dev &&
            git fetch --all &&
            git reset --hard origin/dev &&
            git pull origin dev &&
            export PATH=/home/ubuntu/.nvm/versions/node/v20.17.0/bin:$PATH &&
            npm i &&
            npm i express --save &&
            npm run build
            '
